# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release

on:
  push:
    branches: [ master, 'test-*']
  pull_request:
    branches: [ master, 'test-*' ]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - id: setup-ruby
      name: setup-ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - id: setup-asciidoctor
      name: setup-asciidoctor
      run: |
        gem install asciidoctor
        gem install asciidoctor-diagram
        gem install asciidoctor-pdf
    - id: asciidoctor
      name: asciidoctor
      run: |
        asciidoctor ./docs/index.adoc \
        --backend pdf \
        --require asciidoctor-diagram \
        --require asciidoctor-pdf \
        --out-file ./docs/index.pdf \
        --attribute revnumber="1.0"
    - name: setup semantic-release
      run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D
    - name: release
      run: npx semantic-release
